ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;

ALTER TABLE users ADD CONSTRAINT users_role_check 
CHECK (role IN ('CUSTOMER', 'TECHNICIAN', 'OPERATOR', 'ADMIN', 'USER', 'AGENCY', 'JOB_COMPANY', 'JOB_SEEKER'));